{
    "actions": [
        {
            "install": {
                "action": "savePath", 
                "arguments": {
                    "savePath": "{localappdata}/UNDERTALE", 
                    "type": "folder"
                }
            }, 
            "languages": [
                "*"
            ], 
            "name": "saveFolders"
        }
    ], 
    "productId": "1456487183"
}